config/routes.rb
Nspug::Application.routes.draw do
  resources :maps

  resources :awards

  root 'awards#index'

  

end

app/models/award.rb
class Award < ActiveRecord::Base
end

app/models/map.rb
class Map < ActiveRecord::Base
	#attr_accessible :name, :image
	#validates :name, default: 'unknown name'
	validates :image, presence: true
	mount_uploader :image, ImageUploader

	before_create


	def default_name
		self.name ||= File.basename(image.filename, '.*').titleize if image
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/awards_controller.rb
class AwardsController < ApplicationController

	def index

	end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
	def index
		@maps = Map.all
	end

	def new
		@map = Map.new
	end

	def create
		@map = Map.create(map_params)
		# flash[:notice] =  "Map #{@map.name} succesfully created!"
		# redirect_to maps_path
	end

	def update
		@map = Map.find(params[:id])
	end

	def destroy
		if Map.find(params[:id]).destroy
			flash[:notice] = "deleted!"
			redirect_to maps_path
		else
			flash[:notice] = "unable to delete!"
			redirect_to maps_path
		end
	end

	private
		def map_params
			params.require(:map).permit(:name, :image)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def flash_class(level)
	    case level
		    when :notice then "alert alert-info"
		    when :success then "alert alert-success"
		    when :error then "alert alert-error"
		    when :alert then "alert alert-error"
	    end
	end
end

app/helpers/awards_helper.rb
module AwardsHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nspug</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>


    <div id="notice_message">
      <% flash.each do |key, value| %>
        <div class="<%= flash_class(key) %> fade in">
          <a href="#" data-dismiss="alert" class="close">×</a>
          <%= value %>
        </div>
      <% end %>
    </div>

    
	<%= yield %>

</body>
</html>

app/views/maps/_form.html.erb
<%= form_for @map do |f| %>
	<%#= f.error_messages %>
	<%= f.hidden_field :id %>

	<p>
		<%= f.label :name %><br />
		<%= f.text_field :name %>
	</p>
	<p>
		<%= f.file_field :image %>
	</p>

	<p>
		<%= f.submit %>
	</p>

<% end %>

app/views/maps/_map.html.erb
<li style="border:1px solid black;">
	<%= map.name %>

	<%= image_tag map.image_url(:thumb).to_s %>

	<%= link_to 'delete', map_path(map), method: :delete, confirm: 'you sure??' %>
</li>

app/views/maps/create.js.erb
<% if @map.new_record? %>
	alert("Failed to upload painting: <%= @map.errors.full_messages.join(', ').html() %>");
<% else %>
	$("#maps").append("<%= j render(@map) %>");
<% end %>

app/views/maps/index.html.erb
<%= link_to 'new', new_map_path %>
<ul id="maps">
	<%= render @maps %>
</ul>



<%= form_for Map.new do |f| %>
	<%= f.label :image, "Upload Images:" %>
	<%= f.file_field :image, multiple: true, name: "map[image]" %>
<% end %>

<script id="template-upload" type="text/x-tmpl">
	<div class="upload">
		{%=o.name%}
		<div class="progress">
			<div class="bar" style="border:1px solid black; width: 0%"></div>
		</div>
	</div>

</script>

app/views/maps/new.html.erb
<%= render 'form', map: @map %>

app/views/maps/update.html.erb
<%= render 'form', map: @map %>